//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MANET.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_MANETTYPE                   129
#define IDD_DIALOG_ROUTER               130
#define IDD_DIALOG_CAPTION              131
#define IDR_MENU_ROUTER                 138
#define IDD_DIALOG_LINK                 139
#define IDR_MENU_LINK                   140
#define IDD_DIALOG_TRAFFIC              141
#define IDD_DIALOG_SIMULATION           143
#define IDD_DIALOG_End2End              144
#define IDD_DIALOG_RandomTraffic        145
#define IDD_DIALOG_Stat                 146
#define IDD_DIALOG_ForceSelfishness     147
#define IDB_BITMAP1                     148
#define IDB_Selfish1                    148
#define IDD_DIALOG_GAME                 149
#define IDB_BITMAP2                     150
#define IDD_DIALOG_Protocol             152
#define IDC_EDIT_X                      1000
#define IDC_EDIT_Y                      1001
#define IDC_EDIT_CAPTION                1002
#define IDC_EDIT_LENGTH                 1003
#define IDC_EDIT_COVERAGE               1004
#define IDC_EDIT_DELAY                  1005
#define IDC_EDIT_BUFFER                 1006
#define IDC_EDIT_IMAGE                  1007
#define IDC_EDIT_WIDTH                  1009
#define IDC_EDIT_IN                     1010
#define IDC_EDIT_WIDTH2                 1010
#define IDC_EDIT_Power                  1010
#define IDC_EDIT_OUT                    1011
#define IDC_EDIT_Power2                 1011
#define IDC_EDIT_ForwData               1011
#define IDC_RADIO_GTAMR                 1012
#define IDC_RADIO_AODV                  1013
#define IDC_RADIO_DSR                   1014
#define IDC_EDIT_SOURCE                 1015
#define IDC_EDIT_DESTINATION            1016
#define IDC_SLIDER_MasterSpeed          1019
#define IDC_SLIDER_SlaveSpeed1          1020
#define IDC_SLIDER_SlaveSpeed2          1021
#define IDC_LIST_EVENTS                 1022
#define IDC_BUTTON_ResumeStop           1023
#define IDC_EDIT_FREQUENCY              1024
#define IDC_RADIO_FULL                  1025
#define IDC_RADIO_HALF                  1026
#define IDC_EDIT_ROUTER1                1027
#define IDC_EDIT_ROUTER2                1028
#define IDC_EDIT_START                  1029
#define IDC_RADIO_Adhoc                 1034
#define IDC_RADIO_Malicious             1035
#define IDC_RADIO_Selfish               1036
#define IDC_EDIT_Range                  1037
#define IDC_RADIO_Selfish3              1037
#define IDC_EDIT_Connection             1038
#define IDC_EDIT_DataRate               1039
#define IDC_RADIO_Selfish2              1039
#define IDC_RADIO_AOMDV                 1040
#define IDC_RADIO_Selfish4              1040
#define IDC_EDIT_ProcessedPackets       1041
#define IDC_EDIT_Range2                 1041
#define IDC_EDIT_Stop                   1041
#define IDC_EDIT2                       1042
#define IDC_EDIT_RReqTransNumber        1042
#define IDC_EDIT_RoutersNum             1042
#define IDC_EDIT1                       1044
#define IDC_EDIT_RRepTransNumber        1044
#define IDC_EDIT4                       1046
#define IDC_EDIT5                       1047
#define IDC_EDIT_GenAckTransNumber      1047
#define IDC_RADIO_S1                    1052
#define IDC_RADIO2                      1053
#define IDC_RADIO_S2                    1053
#define IDC_EDIT3                       1054
#define IDC_EDIT_DataTransNumber        1054
#define IDC_EDIT6                       1055
#define IDC_EDIT7                       1056
#define IDC_EDIT8                       1057
#define IDC_EDIT_AdhocNum               1057
#define IDC_EDIT__GenDataTransNumber    1058
#define IDC_EDIT_GenDataTransNumber     1058
#define IDC_EDIT10                      1059
#define IDC_EDIT_Selfish2Num            1059
#define IDC_RADIO_TFT                   1059
#define IDC_EDIT11                      1060
#define IDC_EDIT9                       1060
#define IDC_EDIT_Selfish1Num            1060
#define IDC_RADIO_ERTFT                 1060
#define IDC_EDIT_TotalPower             1061
#define IDC_RADIO_FR                    1061
#define IDC_EDIT_EstabConn              1062
#define IDC_RADIO_TFT2                  1062
#define IDC_EDIT_Tick                   1063
#define IDC_EDIT_Clock                  1063
#define IDC_EDIT_MinDataDelay           1064
#define IDC_EDIT_MaxDataDelay           1065
#define IDC_CHECK1                      1065
#define IDC_EDIT_MinDiscoDelay          1066
#define IDC_EDIT_MaxDiscoDelay          1067
#define IDC_EDIT_AvgDiscoDelay          1068
#define IDC_EDIT_MaxDiscoDelay2         1069
#define IDC_EDIT_AvgDataDelay2          1069
#define ID_NETWORK_ROUTER_ADD           32774
#define ID_NETWORK_ROUTER_EDIT          32775
#define ID_NETWORK_ROUTER_DELETE        32776
#define ID_SIMULATE_RUN                 32777
#define ID_NETWORK_LINK_EDIT            32780
#define ID_NETWORK_LINK_DELETE          32781
#define ID_NETWORK_TRAFFIC_ADD          32782
#define ID_NETWORK_TRAFFIC_EDIT         32783
#define ID_NETWORK_TRAFFIC_DELETE       32784
#define ID_NETWORK_LINK_SELFGENERATE    32789
#define ID_NETWORK_ROUTER_SELFGENERATE_1 32790
#define ID_NETWORK_ROUTER_SELFGENERATE_2 32791
#define ID_NETWORK_ROUTER_SELFGENERATE_5 32792
#define ID_NETWORK_ROUTER_SELFGENERATE_10 32793
#define ID_NETWORK_ROUTER_SELFGENERATE_20 32794
#define ID_NETWORK_ROUTER_SELFGENERATE_50 32795
#define ID_NETWORK_ROUTER_SELFGENERATE_100 32796
#define ID_NETWORK_ROUTER_PREFERENCES   32797
#define ID_ROUTER_ADD                   32801
#define ID_ROUTER_EDIT                  32802
#define ID_ROUTER_DELETE                32803
#define ID_NETWORK_LINK_ROUTERSCLICK    32804
#define ID_LINK_LINKTOHERE              32806
#define ID_LINK_LINKFROMHERE            32807
#define ID_NETWORK_LINK_ADD             32809
#define ID_NETWORK_LINK_UPDATEREDLINKS  32810
#define ID_NETWORK_LINK_REMOVEREDLINKS  32811
#define ID_NETWORK_LINK_CREATEBLUELINKS 32812
#define ID_NETWORK_LINK_DEFAULTPREFERENCES 32813
#define ID_NETWORK_TRAFFIC_SELFGENERATE 32814
#define ID_NETWORK_TRAFFIC_DEFAULTPREFERENCES 32815
#define ID_SIMULATION_STATISTICS_NUMBEROFRREQS 32818
#define ID_SIMULATION_STATISTICS_NUMBEROFRREPS 32819
#define ID_SIMULATION_STATISTICS_NUMBEROFDATAPACKETS 32820
#define ID_SIMULATION_STATISTICS        32821
#define ID_ROUTER_FORCESELFISHNESS      32822
#define ID_FORCESELFISHNESS_TYPEI       32823
#define ID_FORCESELFISHNESS_TYPEII      32824
#define ID_ROUTER_FORCESELFISHNESSII    32825
#define ID_SELF_ANYTYPE                 32826
#define ID_SELF_AD                      32827
#define ID_SELF_SELFISHI                32828
#define ID_SELF_SELFISHII               32829
#define ID_NETWORK_GAME                 32830
#define ID_GAME_DEFAULTPREFERENCES      32831
#define ID_SELF_ALLCONNECTIONS          32832
#define ID_ROUTER_GRID                  32833
#define ID_GRID_64                      32834
#define ID_GRID_100                     32835
#define ID_GRID_250                     32836
#define ID_GRID_225                     32837
#define ID_GRID_144                     32838
#define ID_NETWORK_PROTOCOL             32839
#define ID_PROTOCOL_DEFAULTPREFERENCES  32840

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
